services:
  smolsearch-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: smolsearch-server
    restart: unless-stopped
    environment:
      SmolSearch__DatabasePath: /data/smolsearch.db
    volumes:
      - /opt/smolsearch/data/smolsearch.db:/data/smolsearch.db:ro
      
    ports:
     - "127.0.0.1:55865:8080"
      
    networks:
      - smolsearch

networks:
  smolsearch:
    name: smolsearch
