<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="HappyGemini.Extensibility" Version="0.0.1" ExcludeAssets="runtime" />

		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SmolSearch.Core\SmolSearch.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="happygemini.plugin.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="smolsearch.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
